package trainmanagementgui;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class AddAllocatioin extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

   
    public AddAllocatioin(){
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);

        lblDepartureTime.setVisible(false);
        
      
        dbCon = new myDBCon();
        
        try {
            
            rs = dbCon.executeStatementQuery("SELECT TrainName FROM TRAINLINE ORDER BY TrainID ASC");

            // populate mgr combo box
            while (rs.next()) {
                cmbTrainLine.addItem(rs.getString("TrainName"));
                //cmbRoute.addItem(rs.getString("StationName"));
            }
            
            rs = dbCon.executeStatementQuery("SELECT RouteID FROM TRAINLINE ORDER BY TrainID ASC");

            rs.close();
           
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        getNewRouteId();
    }
    

    
        private void getNewRouteId() {

        String str;
        try {
            // populate CustomerID field
            rs = dbCon.executeStatementQuery("select MAX(RouteID) as RouteID from ROUTES");
        
            while (rs.next()) {
                str = rs.getString("RouteID");
                if (str==null){
                    txtDepartureTime.setText("1");
                }
                else{
                    int temp = Integer.parseInt(str);
                    txtDepartureTime.setText(String.valueOf(++temp));
                }
            }


        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Error Generating RouteID");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    void clearErrorLabels() {
        lblDepartureTime.setText("");
        lblDepartureTime.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDepartureTime = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        cmbTrainLine = new javax.swing.JComboBox<>();
        cmbRoute = new javax.swing.JComboBox<>();
        lblDepartureTime = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAllocationID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTicketCost = new javax.swing.JTextField();
        lbSameSelection1 = new javax.swing.JLabel();
        lblTicketCost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Allocation");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Allocation ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("TrainLine:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Route:");

        txtDepartureTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Create Journey");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        cmbTrainLine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbRoute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblDepartureTime.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblDepartureTime.setForeground(new java.awt.Color(255, 0, 0));
        lblDepartureTime.setText("error label");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Departure Time:");

        txtAllocationID.setEditable(false);
        txtAllocationID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Ticket Cost: ");

        txtTicketCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbSameSelection1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbSameSelection1.setForeground(new java.awt.Color(255, 0, 0));
        lbSameSelection1.setText("error label");

        lblTicketCost.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblTicketCost.setForeground(new java.awt.Color(255, 0, 0));
        lblTicketCost.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddNewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTrainLine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbRoute, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDepartureTime)
                            .addComponent(txtTicketCost, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDepartureTime, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addGap(79, 79, 79))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSameSelection1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTicketCost, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAllocationID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAllocationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTrainLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSameSelection1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartureTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTicketCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTicketCost)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnAddNewEmp)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    boolean isValidData() {
        clearErrorLabels(); 
        boolean result = true;
       

        if (cmbTrainLine.getSelectedItem().toString().equals(cmbRoute.getSelectedItem().toString()) ) {

            lblDepartureTime.setText("Invalid. Origin and Destination Same");

            lblDepartureTime.setVisible(true);
            result = false;
        }
        
       
        return result;
    }



    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {

                
            if (isValidData()) {
                
                //Checks if the route already exists in the table
                rs = dbCon.executeStatementQuery("Select * from ROUTES Where Origin = " +"(Select LocationID FROM LOCATION Where StationName = '"+cmbTrainLine.getSelectedItem().toString() + "')"+" AND Destination = "+ "(Select LocationID FROM LOCATION Where StationName = '"+cmbRoute.getSelectedItem().toString() + "')");
                
                if(!rs.next()){
                    String prepareSQL = "INSERT INTO ROUTES (RouteID, Origin, Destination) VALUES ("
                        + Integer.parseInt(txtDepartureTime.getText())
                        + ", " + "(Select LocationID FROM LOCATION Where StationName = '"+cmbTrainLine.getSelectedItem().toString() + "')"
                        + ", " + "(Select LocationID FROM LOCATION Where StationName = '"+cmbRoute.getSelectedItem().toString() + "'))";
          


                    int result = dbCon.executePreparedStmnt(prepareSQL);

                    if (result > 0) {

                        javax.swing.JLabel label = new javax.swing.JLabel("New Route added successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                        this.dispose();
                    } else {
                        // check validation errors 
                    }      
                }
                else{
                    JOptionPane.showMessageDialog(this, "Same Route Already Exists!!");
                }
                
               
                


            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new Route. "+ e);
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbRoute;
    private javax.swing.JComboBox<String> cmbTrainLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbSameSelection1;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblTicketCost;
    private javax.swing.JTextField txtAllocationID;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtTicketCost;
    // End of variables declaration//GEN-END:variables
}
