package trainmanagementgui;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class AddRoute extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

   
    public AddRoute(){
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);

        lbSameSelection.setVisible(false);
        
      
        dbCon = new myDBCon();
        
        try {
            
            rs = dbCon.executeStatementQuery("SELECT StationName FROM LOCATION ORDER BY LocationID ASC");

            // populate mgr combo box
            while (rs.next()) {
                cmbOrigin.addItem(rs.getString("StationName"));
                cmbDestination.addItem(rs.getString("StationName"));
            }

            rs.close();
           
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        getNewRouteId();
    }
    

    
        private void getNewRouteId() {

        String str;
        try {
            // populate CustomerID field
            rs = dbCon.executeStatementQuery("select MAX(RouteID) as RouteID from ROUTES");
        
            while (rs.next()) {
                str = rs.getString("RouteID");
                if (str==null){
                    txtRouteID.setText("1");
                }
                else{
                    int temp = Integer.parseInt(str);
                    txtRouteID.setText(String.valueOf(++temp));
                }
            }


        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Error Generating RouteID");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
        
    void clearErrorLabels() {
        lbSameSelection.setText("");
        lbSameSelection.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRouteID = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        cmbOrigin = new javax.swing.JComboBox<>();
        cmbDestination = new javax.swing.JComboBox<>();
        lbSameSelection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Route");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Route ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Origin:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Destination:");

        txtRouteID.setEditable(false);
        txtRouteID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Create Route");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        cmbOrigin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbDestination.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbSameSelection.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbSameSelection.setForeground(new java.awt.Color(255, 0, 0));
        lbSameSelection.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddNewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRouteID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOrigin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(lbSameSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRouteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbSameSelection)))
                .addGap(26, 26, 26)
                .addComponent(btnAddNewEmp)
                .addGap(0, 72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    boolean isValidData() {
        clearErrorLabels(); 
        boolean result = true;
       

        if (cmbOrigin.getSelectedItem().toString().equals(cmbDestination.getSelectedItem().toString()) ) {

            lbSameSelection.setText("Invalid. Origin and Destination Same");

            lbSameSelection.setVisible(true);
            result = false;
        }
        
       
        return result;
    }



    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {

                
            if (isValidData()) {
                
                //Checks if the route already exists in the table
                rs = dbCon.executeStatementQuery("Select * from ROUTES Where Origin = " +"(Select LocationID FROM LOCATION Where StationName = '"+cmbOrigin.getSelectedItem().toString() + "')"+" AND Destination = "+ "(Select LocationID FROM LOCATION Where StationName = '"+cmbDestination.getSelectedItem().toString() + "')");
                
                if(!rs.next()){
                    String prepareSQL = "INSERT INTO ROUTES (RouteID, Origin, Destination) VALUES ("
                        + Integer.parseInt(txtRouteID.getText())
                        + ", " + "(Select LocationID FROM LOCATION Where StationName = '"+cmbOrigin.getSelectedItem().toString() + "')"
                        + ", " + "(Select LocationID FROM LOCATION Where StationName = '"+cmbDestination.getSelectedItem().toString() + "'))";
          


                    int result = dbCon.executePreparedStmnt(prepareSQL);

                    if (result > 0) {

                        javax.swing.JLabel label = new javax.swing.JLabel("New Route added successfully.");
                        label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                        JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                        this.dispose();
                    } else {
                        // check validation errors 
                    }      
                }
                else{
                    JOptionPane.showMessageDialog(this, "Same Route Already Exists!!");
                }
                
               
                


            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new Route. "+ e);
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbDestination;
    private javax.swing.JComboBox<String> cmbOrigin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbSameSelection;
    private javax.swing.JTextField txtRouteID;
    // End of variables declaration//GEN-END:variables
}
