package trainmanagementgui;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddTrainline extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;

   
    public AddTrainline(){
        initComponents();
        
        // center form in screen 
        this.setLocationRelativeTo(null);
        // set all error labels to invisible
        lbTrainNameError.setVisible(false);
        lblPassengerCapError.setVisible(false);
        
        
      
        dbCon = new myDBCon();
        getNewTrainId();
        //populate mgr and deptno combo boxes 
       

    }
    
        private void getNewTrainId() {

        String str;
        try {
            // populate CustomerID field
            rs = dbCon.executeStatementQuery("select MAX(TrainID) as TrainID from TRAINLINE");
        
            while (rs.next()) {
                str = rs.getString("TrainID");
                if (str==null){
                    txtTrainID.setText("1");
                }
                else{
                    int temp = Integer.parseInt(str);
                    txtTrainID.setText(String.valueOf(++temp));
                }
            }


        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Error Generating CustomerID");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTrainID = new javax.swing.JTextField();
        txtTrainName = new javax.swing.JTextField();
        txtPassengerCap = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblPassengerCapError = new javax.swing.JLabel();
        lbTrainNameError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New TrainLine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TrainID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Train Name: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Passenger Capacity:");

        txtTrainID.setEditable(false);
        txtTrainID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtTrainName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPassengerCap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassengerCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassengerCapActionPerformed(evt);
            }
        });

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Add Trainline");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblPassengerCapError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPassengerCapError.setForeground(new java.awt.Color(255, 0, 0));
        lblPassengerCapError.setText("error label");

        lbTrainNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbTrainNameError.setForeground(new java.awt.Color(255, 0, 0));
        lbTrainNameError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTrainName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtPassengerCap))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTrainNameError, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(lblPassengerCapError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnAddNewEmp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 187, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTrainID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrainName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTrainNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassengerCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassengerCapError))
                .addGap(45, 45, 45)
                .addComponent(btnAddNewEmp)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassengerCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassengerCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassengerCapActionPerformed

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    
    //clears alll the error labels
    void clearErrorLabels() {
      
        lbTrainNameError.setText("");
        lbTrainNameError.setVisible(false);
        lblPassengerCapError.setText("");
        lblPassengerCapError.setVisible(false);
        

    }

    boolean isValidData() {

        clearErrorLabels(); //clears all error labels
        boolean result = true;
       

        if (txtTrainName.getText().trim().isEmpty() || (txtTrainName.getText().trim().length() > 25)) {
            if (txtTrainName.getText().trim().isEmpty()) {
                lbTrainNameError.setText("Invalid. Cannot be empty.");
            } else if ((txtTrainName.getText().trim().length() > 25)) {
                lbTrainNameError.setText("Invalid. Must be < 25 chars.");
            }

            lbTrainNameError.setVisible(true);
            result = false;
        }

        if (txtPassengerCap.getText().trim().isEmpty() || !isInteger(txtPassengerCap.getText().trim())) {
            if (txtPassengerCap.getText().trim().isEmpty()) {
                lblPassengerCapError.setText("Invalid. Cannot be empty.");
            } else if (!isInteger(txtPassengerCap.getText().trim())) {
                lblPassengerCapError.setText("Invalid. Must be integer");
            }
            lblPassengerCapError.setVisible(true);
            result = false;
        }

        return result;
    }

    void clearInputBoxes() {
        txtTrainID.setText("");
        txtTrainName.setText("");
        txtPassengerCap.setText("");
    }

    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {

                
            if (isValidData()) {
                
                //Inserts new employee data into the emp table after validation
                String prepareSQL = "INSERT INTO Trainline (TrainID, TrainName, PassengerCapacity) VALUES ("
                        + Integer.parseInt(txtTrainID.getText())
                        + ",'" + txtTrainName.getText().toUpperCase() + "'"
                        + ", " + Integer.parseInt(txtPassengerCap.getText()) + ")";

                int result = dbCon.executePreparedStmnt(prepareSQL);

                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New Trainline added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    clearInputBoxes();
                    this.dispose();
                } else {
                    // check validation errors 
                }


            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new Trainline.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbTrainNameError;
    private javax.swing.JLabel lblPassengerCapError;
    private javax.swing.JTextField txtPassengerCap;
    private javax.swing.JTextField txtTrainID;
    private javax.swing.JTextField txtTrainName;
    // End of variables declaration//GEN-END:variables
}
